/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Oscar
 */
public class Home extends javax.swing.JFrame {
    AdvancedLinkedList cocineros = new AdvancedLinkedList();
    Pila ingredientes = new Pila();
    Cola ordenes = new Cola();
    
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        System.out.println("HELLO");
        cocineros.insert(new Cocineros());
        cocineros.insert(new Cocineros());
        cocineros.insert(new Cocineros());
        cocineros.insert(new Cocineros());
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        AddIngre = new javax.swing.JLabel();
        EditIngre = new javax.swing.JLabel();
        RemoveIngre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Order = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        deleteOrder = new javax.swing.JLabel();
        newOrder = new javax.swing.JLabel();
        editOrder = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddDish = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_dishName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_inameDesc = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ingredients_dish = new javax.swing.JComboBox();
        sp_timedish = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        sp_pricedish = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        EditDish = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Dish_tableIngredients = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        EditselectDish = new javax.swing.JComboBox();
        Editingredients_dish = new javax.swing.JComboBox();
        Editsp_timedish = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        Editsp_pricedish = new javax.swing.JSpinner();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Edittf_Desc = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        Edittf_dishName = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DeleteDish = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        DeleteselectDish = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        AddOrder = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        tf_inameDesc1 = new javax.swing.JTextField();
        tf_dishName1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sp_timedish1 = new javax.swing.JSpinner();
        sp_pricedish1 = new javax.swing.JSpinner();
        jLabel43 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        ingredients_dish1 = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        EditOrder = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        Order_remDish = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        EditselectOrder = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        tf_clientOrderE = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        Order_addDish = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel56 = new javax.swing.JLabel();
        sp_pricedish2 = new javax.swing.JSpinner();
        jLabel57 = new javax.swing.JLabel();
        sp_timedish2 = new javax.swing.JSpinner();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        DeleteOrder = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        DeleteselectDish1 = new javax.swing.JComboBox();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        NewIngredient = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        tf_ingName = new javax.swing.JTextField();
        tf_ingDesc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cellar = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        food = new javax.swing.JLabel();
        meramera = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });

        jPanel2.setLayout(null);

        AddIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/NewDish.png"))); // NOI18N
        AddIngre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddIngreMouseClicked(evt);
            }
        });
        jPanel2.add(AddIngre);
        AddIngre.setBounds(30, 40, 174, 40);

        EditIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/EditDish.png"))); // NOI18N
        EditIngre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditIngreMouseClicked(evt);
            }
        });
        jPanel2.add(EditIngre);
        EditIngre.setBounds(30, 100, 174, 40);

        RemoveIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/DeleteDish.png"))); // NOI18N
        RemoveIngre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveIngreMouseClicked(evt);
            }
        });
        jPanel2.add(RemoveIngre);
        RemoveIngre.setBounds(30, 160, 174, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconDish.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(220, -10, 280, 260);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 490, 250);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu.getContentPane());
        Menu.getContentPane().setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setLayout(null);

        deleteOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/DeleteOrder.png"))); // NOI18N
        deleteOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteOrderMouseClicked(evt);
            }
        });
        jPanel4.add(deleteOrder);
        deleteOrder.setBounds(320, 170, 190, 40);

        newOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/NewOrder.png"))); // NOI18N
        newOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newOrderMouseClicked(evt);
            }
        });
        jPanel4.add(newOrder);
        newOrder.setBounds(320, 50, 191, 40);

        editOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/EditOrder.png"))); // NOI18N
        editOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editOrderMouseClicked(evt);
            }
        });
        jPanel4.add(editOrder);
        editOrder.setBounds(320, 110, 190, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconOrder.png"))); // NOI18N
        jPanel4.add(jLabel11);
        jLabel11.setBounds(-40, 0, 370, 260);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 0, 550, 260);

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order.getContentPane());
        Order.getContentPane().setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top1.png"))); // NOI18N
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 20, 511, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconListIng.png"))); // NOI18N
        jPanel5.add(jLabel12);
        jLabel12.setBounds(70, 290, 140, 29);
        jPanel5.add(tf_dishName);
        tf_dishName.setBounds(220, 130, 210, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconTime.png"))); // NOI18N
        jPanel5.add(jLabel27);
        jLabel27.setBounds(150, 250, 60, 30);
        jPanel5.add(tf_inameDesc);
        tf_inameDesc.setBounds(220, 170, 210, 30);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconName.png"))); // NOI18N
        jPanel5.add(jLabel30);
        jLabel30.setBounds(130, 130, 80, 29);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconDesc.png"))); // NOI18N
        jPanel5.add(jLabel31);
        jLabel31.setBounds(70, 170, 140, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel5.add(jLabel28);
        jLabel28.setBounds(130, 350, 130, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel29.setToolTipText("");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(280, 350, 121, 40);

        ingredients_dish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(ingredients_dish);
        ingredients_dish.setBounds(220, 290, 210, 30);
        jPanel5.add(sp_timedish);
        sp_timedish.setBounds(220, 250, 70, 30);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconPrice.png"))); // NOI18N
        jPanel5.add(jLabel32);
        jLabel32.setBounds(140, 210, 69, 30);
        jPanel5.add(sp_pricedish);
        sp_pricedish.setBounds(220, 210, 110, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel13.setToolTipText("");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(0, 0, 530, 440);

        javax.swing.GroupLayout AddDishLayout = new javax.swing.GroupLayout(AddDish.getContentPane());
        AddDish.getContentPane().setLayout(AddDishLayout);
        AddDishLayout.setHorizontalGroup(
            AddDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AddDishLayout.setVerticalGroup(
            AddDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDishLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top3.png"))); // NOI18N
        jPanel6.add(jLabel15);
        jLabel15.setBounds(20, 20, 510, 80);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel33.setToolTipText("");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(280, 460, 121, 40);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel6.add(jLabel34);
        jLabel34.setBounds(130, 460, 130, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconListIng.png"))); // NOI18N
        jPanel6.add(jLabel35);
        jLabel35.setBounds(90, 310, 140, 29);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingridient", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Dish_tableIngredients.setViewportView(jTable3);

        jPanel6.add(Dish_tableIngredients);
        Dish_tableIngredients.setBounds(90, 350, 360, 80);

        EditselectDish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(EditselectDish);
        EditselectDish.setBounds(250, 110, 160, 30);

        Editingredients_dish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(Editingredients_dish);
        Editingredients_dish.setBounds(240, 310, 170, 30);
        jPanel6.add(Editsp_timedish);
        Editsp_timedish.setBounds(240, 270, 70, 30);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconTime.png"))); // NOI18N
        jPanel6.add(jLabel36);
        jLabel36.setBounds(170, 270, 60, 30);
        jPanel6.add(Editsp_pricedish);
        Editsp_pricedish.setBounds(240, 230, 110, 30);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconPrice.png"))); // NOI18N
        jPanel6.add(jLabel37);
        jLabel37.setBounds(160, 230, 69, 30);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconDesc.png"))); // NOI18N
        jPanel6.add(jLabel38);
        jLabel38.setBounds(90, 190, 140, 30);
        jPanel6.add(Edittf_Desc);
        Edittf_Desc.setBounds(240, 190, 210, 30);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconName.png"))); // NOI18N
        jPanel6.add(jLabel39);
        jLabel39.setBounds(150, 150, 80, 29);
        jPanel6.add(Edittf_dishName);
        Edittf_dishName.setBounds(240, 150, 210, 30);

        jLabel40.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 255, 0));
        jLabel40.setText("Select Dish");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(100, 110, 170, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel16.setToolTipText("");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(0, 0, 530, 530);

        javax.swing.GroupLayout EditDishLayout = new javax.swing.GroupLayout(EditDish.getContentPane());
        EditDish.getContentPane().setLayout(EditDishLayout);
        EditDishLayout.setHorizontalGroup(
            EditDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        EditDishLayout.setVerticalGroup(
            EditDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditDishLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top2.png"))); // NOI18N
        jPanel7.add(jLabel17);
        jLabel17.setBounds(20, 20, 580, 80);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel7.add(jLabel44);
        jLabel44.setBounds(120, 180, 130, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel45.setToolTipText("");
        jPanel7.add(jLabel45);
        jLabel45.setBounds(270, 180, 121, 40);

        jLabel46.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 255, 0));
        jLabel46.setText("Select Dish");
        jPanel7.add(jLabel46);
        jLabel46.setBounds(100, 120, 170, 30);

        DeleteselectDish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DeleteselectDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteselectDishActionPerformed(evt);
            }
        });
        jPanel7.add(DeleteselectDish);
        DeleteselectDish.setBounds(250, 120, 160, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel18.setToolTipText("");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(0, 0, 530, 260);

        javax.swing.GroupLayout DeleteDishLayout = new javax.swing.GroupLayout(DeleteDish.getContentPane());
        DeleteDish.getContentPane().setLayout(DeleteDishLayout);
        DeleteDishLayout.setHorizontalGroup(
            DeleteDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DeleteDishLayout.setVerticalGroup(
            DeleteDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(70, 240, 390, 90);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconNumber.png"))); // NOI18N
        jPanel8.add(jLabel50);
        jLabel50.setBounds(107, 120, 103, 29);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconClient.png"))); // NOI18N
        jPanel8.add(jLabel51);
        jLabel51.setBounds(130, 160, 80, 30);
        jPanel8.add(tf_inameDesc1);
        tf_inameDesc1.setBounds(220, 160, 210, 30);
        jPanel8.add(tf_dishName1);
        tf_dishName1.setBounds(220, 120, 210, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top4.png"))); // NOI18N
        jPanel8.add(jLabel19);
        jLabel19.setBounds(0, 20, 520, 80);
        jPanel8.add(sp_timedish1);
        sp_timedish1.setBounds(360, 340, 70, 30);
        jPanel8.add(sp_pricedish1);
        sp_pricedish1.setBounds(190, 340, 70, 30);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconTotal.png"))); // NOI18N
        jPanel8.add(jLabel43);
        jLabel43.setBounds(100, 340, 80, 30);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/dish.png"))); // NOI18N
        jPanel8.add(jLabel47);
        jLabel47.setBounds(100, 200, 110, 29);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconTime.png"))); // NOI18N
        jPanel8.add(jLabel52);
        jLabel52.setBounds(290, 340, 60, 30);

        ingredients_dish1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(ingredients_dish1);
        ingredients_dish1.setBounds(220, 200, 210, 30);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel8.add(jLabel48);
        jLabel48.setBounds(130, 410, 130, 40);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel49.setToolTipText("");
        jPanel8.add(jLabel49);
        jLabel49.setBounds(280, 410, 121, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel41.setToolTipText("");
        jPanel8.add(jLabel41);
        jLabel41.setBounds(0, 0, 530, 500);

        javax.swing.GroupLayout AddOrderLayout = new javax.swing.GroupLayout(AddOrder.getContentPane());
        AddOrder.getContentPane().setLayout(AddOrderLayout);
        AddOrderLayout.setHorizontalGroup(
            AddOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AddOrderLayout.setVerticalGroup(
            AddOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddOrderLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setLayout(null);

        Order_remDish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(Order_remDish);
        Order_remDish.setBounds(220, 230, 210, 30);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/dishR.png"))); // NOI18N
        jPanel9.add(jLabel60);
        jLabel60.setBounds(70, 230, 140, 29);

        jLabel42.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 255, 0));
        jLabel42.setText("Select Order");
        jPanel9.add(jLabel42);
        jLabel42.setBounds(100, 110, 170, 30);

        EditselectOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EditselectOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditselectOrderActionPerformed(evt);
            }
        });
        jPanel9.add(EditselectOrder);
        EditselectOrder.setBounds(270, 110, 150, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top6.png"))); // NOI18N
        jPanel9.add(jLabel21);
        jLabel21.setBounds(0, 20, 510, 80);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconClient.png"))); // NOI18N
        jPanel9.add(jLabel54);
        jLabel54.setBounds(130, 150, 80, 30);
        jPanel9.add(tf_clientOrderE);
        tf_clientOrderE.setBounds(220, 150, 210, 30);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/dish.png"))); // NOI18N
        jPanel9.add(jLabel55);
        jLabel55.setBounds(100, 190, 110, 29);

        Order_addDish.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(Order_addDish);
        Order_addDish.setBounds(220, 190, 210, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel9.add(jScrollPane2);
        jScrollPane2.setBounds(70, 280, 390, 90);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconTotal.png"))); // NOI18N
        jPanel9.add(jLabel56);
        jLabel56.setBounds(100, 380, 80, 30);
        jPanel9.add(sp_pricedish2);
        sp_pricedish2.setBounds(190, 380, 70, 30);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconTime.png"))); // NOI18N
        jPanel9.add(jLabel57);
        jLabel57.setBounds(290, 380, 60, 30);
        jPanel9.add(sp_timedish2);
        sp_timedish2.setBounds(360, 380, 70, 30);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel9.add(jLabel58);
        jLabel58.setBounds(130, 430, 130, 40);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel59.setToolTipText("");
        jPanel9.add(jLabel59);
        jLabel59.setBounds(280, 430, 121, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel22.setToolTipText("");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(0, 0, 530, 500);

        javax.swing.GroupLayout EditOrderLayout = new javax.swing.GroupLayout(EditOrder.getContentPane());
        EditOrder.getContentPane().setLayout(EditOrderLayout);
        EditOrderLayout.setHorizontalGroup(
            EditOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        EditOrderLayout.setVerticalGroup(
            EditOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditOrderLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setLayout(null);

        jLabel53.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 255, 0));
        jLabel53.setText("Select Order");
        jPanel10.add(jLabel53);
        jLabel53.setBounds(100, 120, 170, 30);

        DeleteselectDish1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DeleteselectDish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteselectDish1ActionPerformed(evt);
            }
        });
        jPanel10.add(DeleteselectDish1);
        DeleteselectDish1.setBounds(270, 120, 140, 30);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel10.add(jLabel61);
        jLabel61.setBounds(120, 180, 130, 40);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel62.setToolTipText("");
        jPanel10.add(jLabel62);
        jLabel62.setBounds(270, 180, 121, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top5.png"))); // NOI18N
        jPanel10.add(jLabel23);
        jLabel23.setBounds(0, 20, 530, 80);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel24.setToolTipText("");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(0, 0, 530, 300);

        javax.swing.GroupLayout DeleteOrderLayout = new javax.swing.GroupLayout(DeleteOrder.getContentPane());
        DeleteOrder.getContentPane().setLayout(DeleteOrderLayout);
        DeleteOrderLayout.setHorizontalGroup(
            DeleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DeleteOrderLayout.setVerticalGroup(
            DeleteOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel11.setLayout(null);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Top7.png"))); // NOI18N
        jLabel25.setLabelFor(AddIngre);
        jPanel11.add(jLabel25);
        jLabel25.setBounds(20, 20, 580, 80);
        jPanel11.add(tf_ingName);
        tf_ingName.setBounds(220, 140, 210, 30);
        jPanel11.add(tf_ingDesc);
        tf_ingDesc.setBounds(220, 180, 210, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconDesc.png"))); // NOI18N
        jPanel11.add(jLabel9);
        jLabel9.setBounds(70, 180, 140, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconName.png"))); // NOI18N
        jPanel11.add(jLabel10);
        jLabel10.setBounds(130, 140, 80, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel11.add(jLabel5);
        jLabel5.setBounds(280, 240, 121, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/accept.png"))); // NOI18N
        jPanel11.add(jLabel8);
        jLabel8.setBounds(130, 240, 130, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jLabel26.setToolTipText("");
        jPanel11.add(jLabel26);
        jLabel26.setBounds(0, 0, 530, 320);

        javax.swing.GroupLayout NewIngredientLayout = new javax.swing.GroupLayout(NewIngredient.getContentPane());
        NewIngredient.getContentPane().setLayout(NewIngredientLayout);
        NewIngredientLayout.setHorizontalGroup(
            NewIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        NewIngredientLayout.setVerticalGroup(
            NewIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewIngredientLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 240, 170);

        cellar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cellar.png"))); // NOI18N
        cellar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cellarMouseClicked(evt);
            }
        });
        jPanel1.add(cellar);
        cellar.setBounds(40, 230, 250, 50);

        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/order.png"))); // NOI18N
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });
        jPanel1.add(order);
        order.setBounds(40, 350, 250, 50);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/menu.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(40, 290, 250, 50);

        food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/food.png"))); // NOI18N
        jPanel1.add(food);
        food.setBounds(310, 90, 450, 320);

        meramera.setFont(new java.awt.Font("Eras Medium ITC", 1, 36)); // NOI18N
        meramera.setForeground(new java.awt.Color(255, 255, 255));
        meramera.setText("La Mera Mera ");
        jPanel1.add(meramera);
        meramera.setBounds(320, 40, 260, 43);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/links.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(580, 40, 173, 52);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/black1926.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cellarMouseClicked
        NewIngredient.pack();
        NewIngredient.setModal(true);
        NewIngredient.setLocationRelativeTo(null);
        NewIngredient.setVisible(true);
    }//GEN-LAST:event_cellarMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        Order.pack();
        Order.setModal(true);
        Order.setLocationRelativeTo(null);
        Order.setVisible(true);
    }//GEN-LAST:event_orderMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        Menu.pack();
        Menu.setModal(true);
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
    }//GEN-LAST:event_menuMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMouseClicked

    private void AddIngreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddIngreMouseClicked
        System.out.println("New Dish Button");        
        AddDish.pack();
        AddDish.setModal(true);
        AddDish.setLocationRelativeTo(null);
        AddDish.setVisible(true);
        
    }//GEN-LAST:event_AddIngreMouseClicked

    private void EditIngreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditIngreMouseClicked
        System.out.println("Edit Dish Button");
        EditDish.pack();
        EditDish.setModal(true);
        EditDish.setLocationRelativeTo(null);
        EditDish.setVisible(true);
    }//GEN-LAST:event_EditIngreMouseClicked

    private void RemoveIngreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveIngreMouseClicked
        System.out.println("Delete Dish Button");
        DeleteDish.pack();
        DeleteDish.setModal(true);
        DeleteDish.setLocationRelativeTo(null);
        DeleteDish.setVisible(true);
    }//GEN-LAST:event_RemoveIngreMouseClicked

    private void newOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrderMouseClicked
        AddOrder.pack();
        AddOrder.setModal(true);
        AddOrder.setLocationRelativeTo(null);
        AddOrder.setVisible(true);
    }//GEN-LAST:event_newOrderMouseClicked

    private void editOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editOrderMouseClicked
        EditOrder.pack();
        EditOrder.setModal(true);
        EditOrder.setLocationRelativeTo(null);
        EditOrder.setVisible(true);
    }//GEN-LAST:event_editOrderMouseClicked

    private void deleteOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteOrderMouseClicked
        DeleteOrder.pack();
        DeleteOrder.setModal(true);
        DeleteOrder.setLocationRelativeTo(null);
        DeleteOrder.setVisible(true);
    }//GEN-LAST:event_deleteOrderMouseClicked

<<<<<<< HEAD
    private void AgregarIngrediente(java.awt.event.MouseEvent evt){
        ingredientes.push(new Ingridient("String","String2"));
    }
    
    
  
    
=======
    private void DeleteselectDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteselectDishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteselectDishActionPerformed

    private void EditselectOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditselectOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditselectOrderActionPerformed

    private void DeleteselectDish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteselectDish1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteselectDish1ActionPerformed

>>>>>>> e50704584551fb60415aaf501b7039ca128ff42e
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddDish;
    private javax.swing.JLabel AddIngre;
    private javax.swing.JDialog AddOrder;
    private javax.swing.JDialog DeleteDish;
    private javax.swing.JDialog DeleteOrder;
    private javax.swing.JComboBox DeleteselectDish;
    private javax.swing.JComboBox DeleteselectDish1;
    private javax.swing.JScrollPane Dish_tableIngredients;
    private javax.swing.JDialog EditDish;
    private javax.swing.JLabel EditIngre;
    private javax.swing.JDialog EditOrder;
    private javax.swing.JComboBox Editingredients_dish;
    private javax.swing.JComboBox EditselectDish;
    private javax.swing.JComboBox EditselectOrder;
    private javax.swing.JSpinner Editsp_pricedish;
    private javax.swing.JSpinner Editsp_timedish;
    private javax.swing.JTextField Edittf_Desc;
    private javax.swing.JTextField Edittf_dishName;
    private javax.swing.JDialog Menu;
    private javax.swing.JDialog NewIngredient;
    private javax.swing.JDialog Order;
    private javax.swing.JComboBox Order_addDish;
    private javax.swing.JComboBox Order_remDish;
    private javax.swing.JLabel RemoveIngre;
    private javax.swing.JLabel cellar;
    private javax.swing.JLabel deleteOrder;
    private javax.swing.JLabel editOrder;
    private javax.swing.JLabel food;
    private javax.swing.JComboBox ingredients_dish;
    private javax.swing.JComboBox ingredients_dish1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel meramera;
    private javax.swing.JLabel newOrder;
    private javax.swing.JLabel order;
    private javax.swing.JSpinner sp_pricedish;
    private javax.swing.JSpinner sp_pricedish1;
    private javax.swing.JSpinner sp_pricedish2;
    private javax.swing.JSpinner sp_timedish;
    private javax.swing.JSpinner sp_timedish1;
    private javax.swing.JSpinner sp_timedish2;
    private javax.swing.JTextField tf_clientOrderE;
    private javax.swing.JTextField tf_dishName;
    private javax.swing.JTextField tf_dishName1;
    private javax.swing.JTextField tf_inameDesc;
    private javax.swing.JTextField tf_inameDesc1;
    private javax.swing.JTextField tf_ingDesc;
    private javax.swing.JTextField tf_ingName;
    // End of variables declaration//GEN-END:variables
}
